name: Deploy to Azure kube Instance

on:
  workflow_run:
    workflows: ["Training and Docker Build Pipeline"]  # Name of the first workflow (train.yml)
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest  #(it is machine for github action workflow , all the task run on this machine)
    steps:
      - name: Checkout code    #(fetching the repositery(frtch all the codes))
        uses: actions/checkout@v2

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
      
      # - name: Azure login
      #   run: az login

      - name: subscription set for aks
        run: az account set --subscription db962ab2-7e93-4bc4-88a4-49e99f7ee55d     

      - name: credential setup
        run: az aks get-credentials --resource-group iris_actions_demo --name Actions_demo --overwrite-existing

      - name: running the deployment file 
        run: kubectl apply -f deployment.yaml

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: install the required dependencies for unit test cases
        run: pip install pytest httpx

      - name: run the unit test file
        run: pytest python_test.py    


      # - name: Azure login
      #   run: az login